import type { Product } from "../types";

export const products: Product[] = [
    {
        id : "1",
        name: "Nike cortez",
        price: 190.99,
        imageUrl : "/imagesProducts/nike-cortez.webp",
        brand : "Nike",  
    },
    {
        id : "2",
        name: "Nike 700",
        price: 170.99,
        imageUrl : "/imagesProducts/nike-700.webp",
        brand : "Nike",   
    },  
    {
        id: "3",
        name:"Nike dunk low",
        price : 199.99,
        imageUrl:"/imagesProducts/nike-dunk-low.webp",
        brand : "Nike",  
    },
    {
        id: "4",
        name:"Nike Genesis",
        price : 199.99,
        imageUrl:"/imagesProducts/nike-genesis.webp",
        brand : "Nike",  
    },
    {
        id: "5",
        name:"Adidas Yeezy",
        price : 219.99,
        imageUrl:"/imagesProducts/adidas-yeezy.webp",
        brand : "Adidas",  
    },
    {
        id: "6",
        name:"Adidas Yeezy Black",
        price : 219.99,
        imageUrl:"/imagesProducts/adidas-yeezy-black.webp",
        brand : "Adidas",  
    },
    {
        id: "7",
        name:"Adidas X ghoster",
        price : 219.99,
        imageUrl:"/imagesProducts/adidasXghoster.webp",
        brand : "Adidas",  
    },
    {
        id: "8",
        name:"Nike Abundance",
        price : 222.99,
        imageUrl:"/imagesProducts/nike-abundance.webp",
        brand : "Nike",  
    },
    {
        id: "9",
        name:"Nike Air Max 1",
        price : 119.99,
        imageUrl:"/imagesProducts/nike-air-max-1.webp",
        brand : "Nike",  
    },
    {
        id: "10",
        name:"Vomero Nike",
        price : 120.99,
        imageUrl:"/imagesProducts/vomero-nike.webp",
        brand : "Nike",  
    },
    {
        id: "11",
        name: "Adidas superstar negro",
        price: 140.99,
        imageUrl: "/imagesProducts/adidas-superstar-negro.webp",
        brand : "Adidas",  
    },
    {
        id: "12",
        name: "Jordan Heir Sail",
        price: 300.00,
        imageUrl: "/imagesProducts/jordan-heir-sail.webp",
        brand : "Nike",  
    },
    {
        id: "13",
        name: "Adidas Evo",
        price: 129.99,
        imageUrl: "/imagesProducts/adidas-evo.webp",
        brand : "Adidas",  
    },
    {
        id: "14",
        name: "Air Jordan Zion 4",
        price: 140.00,
        imageUrl: "/imagesProducts/jordan-zion-4.webp",
        brand : "Nike",  
    },
    {
        id: "15",
        name: "Nike Concepts",
        price: 150.00,
        imageUrl: "/imagesProducts/nike-concepts.webp",
        brand : "Nike", 
    },
    {
        id: "16",
        name: "Nike Shox Black",
        price: 129.00,
        imageUrl: "/imagesProducts/nike-shox-black.webp",
        brand: "Nike", 
    },
    {
        id: "17",
        name: "Nike TN blue",
        price: 189.99,
        imageUrl: "/imagesProducts/nike-tn-blue.webp",
        brand: "Nike", 
    },
    {
        id: "18",
        name: "Nike Tuned",
        price: 170.99,
        imageUrl: "/imagesProducts/nike-tuned.webp",
        brand: "Nike", 
    },
    {
        id: "19",
        name: "Superstar Sean",
        price: 200.00,
        imageUrl: "/imagesProducts/superstar-sean.webp",
        brand: "Adidas", 
    },
    {
        id: "20",
        name: "Air Retro 4 Wet Cement",
        price: 299.99,
        imageUrl: "/imagesProducts/retro-4-wet-cement.webp",
        brand: "Nike", 
    },
    {
        id: "21",
        name: "Air Retro haze",
        price: 299.99,
        imageUrl: "/imagesProducts/retro-sp-haze.webp",
        brand: "Nike", 
    },
    {
        id: "22",
        name: "Louis Vuitton Black",
        price: 999.00,
        imageUrl: "/imagesProducts/louis-vuitton-black.webp",
        brand: "Louis Vuitton", 

    },
    {
        id: "23",
        name: "Louis Vuitton Cream",
        price: 999.00,
        imageUrl: "/imagesProducts/louis-vuitton-cream.webp",
        brand: "Louis Vuitton", 
    },
    {
        id: "24",
        name: "Nike Dior",
        price: 599.00,
        imageUrl: "/imagesProducts/nike-dior.webp",
        soldOut: true,
        brand: "Nike", 
    },
]